### ISSUE TITLE
file picker crashes sometimes (rarely)

### ISSUE THREAD

**Issue by rand99** [murlokswarm/mac#22]
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fffc627e05d]

runtime stack:
runtime.throw(0x421107d, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x419ad60, 0xc420057ec8, 0xc400000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420057e98 sp=0xc420057e58
ccc_batch_export/vendor/github.com/murlokswarm/mac._Cfunc_Driver_Run()
	??:0 +0x41 fp=0xc420057ec8 sp=0xc420057e98
ccc_batch_export/vendor/github.com/murlokswarm/mac.(*Driver).Run(0xc420016c30)
	/Users/user/code/go/src/ccc_batch_export/vendor/github.com/murlokswarm/mac/driver.go:54 +0x1d fp=0xc420057ed0 sp=0xc420057ec8
ccc_batch_export/vendor/github.com/murlokswarm/app.Run()
	/Users/user/code/go/src/ccc_batch_export/vendor/github.com/murlokswarm/app/app.go:49 +0x35 fp=0xc420057ee8 sp=0xc420057ed0
main.main()
	/Users/user/code/go/src/ccc_batch_export/m_main.go:59 +0xc0 fp=0xc420057f48 sp=0xc420057ee8
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420057fa0 sp=0xc420057f48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420057fa8 sp=0xc420057fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
```

**Comment by maxence-charriere** [comment]
can you give me a little more context?
Is the filePicker is called from a button in a window or is it called when there is no window?

**Comment by rand99** [comment]
Yes it is called from a window.

`<input type="button"  class="btns" value="Select .als file"  onclick="OnOpenProjectFile"/>`

```
func (h *ClipExporterView) OnOpenProjectFile(arg app.ChangeArg) {
	h.ErrorAlsFile = ""
	app.NewFilePicker(app.FilePicker{
		MultipleSelection: false,
		NoDir:             true,
		NoFile:            false,
		OnPick: func(filenames []string) {
			h.AlsFile = filenames[0]
			ok, err := file_exists(h.AlsFile)
			if !ok {
				h.Error = err.Error()
				h.AlsFile = ""
			}

			app.Render(h)
		},
	})
}
```
